### ISSUE TITLE
Snippets not showing

### ISSUE THREAD

**Issue by Zpiboo** [jsitor/jsitor#110]
On the IOS app, no snippet shows. I then tried to disconnect-reconnect, but when logging back in it shows me an error that tells me the certificate is invalid or something like that: I selected "Continue without account" and cannot exit that mode (I can only click on "Log in", which gives me an error) to test it again and copy the message. It seems to work on a web browser.

**Comment by ashvin777** [comment]
Please try again, we have fixed the certificate issue.

**Comment by Zpiboo** [comment]
Thank you, it works fine now.

________________________________
De : Ashvin Kumar Suthar ***@***.***>
Envoyé : dimanche 14 août 2022 01:43
À : jsitor/jsitor ***@***.***>
Cc : Zpiboo ***@***.***>; Author ***@***.***>
Objet : Re: [jsitor/jsitor] Snippets not showing (Issue #110)


Please try again, we have fixed the certificate issue.
