### ISSUE TITLE
jsitor page down

### ISSUE THREAD

**Issue by MagnoAlberto** [jsitor/jsitor#137]
Since yesterday (2023-09-13), when trying to access the page (https://jsitor.com/), it keeps "trying to load" and stays like this infinitely. 
Tests were carried out on 3 different browsers (chrome, edge, firefox)

![image](https://github.com/jsitor/jsitor/assets/89164611/55120b62-386a-42f3-bb3f-e87f4b576531)

**Comment by inderpreethanda** [comment]
It is still not working for me. is it working for anyone?

**Comment by MagnoAlberto** [comment]
Not yet (2023-09-16), It's a shame =[, for me it's much better than codepen and jsfiddle.

**Comment by jobayer977** [comment]
Still I'm having same issues

**Comment by LeightonFerris** [comment]
I am also no longer able to access the site. I had some cool widgets saved there too. :(

**Comment by mikeyhodl** [comment]
I cant access it too, create a donation we put it back up

**Comment by ashvin777** [comment]
Thank you for your response. It happened because the SSL certificate was
expired. Its now updated. Please try now.

**Comment by MagnoAlberto** [comment]
omg... the jsitor is online and functional, ty!

**Comment by HRC123456789ha** [comment]
it is no longer open for microsoft edge
