### ISSUE TITLE
Clipboard 

### ISSUE THREAD

**Issue by AustinRobinson** [jsitor/jsitor#15]
Pasting does not work in editor but works in title box. It always wants to copy even if the clipboard isn’t empty.

**Comment by ashvin777** [comment]
Thanks @AustinRobinson for your feedback. I will reproduce and will add a fix for it. Let me know if you are facing any other issues or you have suggestions/improvements.

Thanks for using JSitor. :)

**Comment by ashvin777** [comment]
This issue has been resolved in v1.30. I am marking this closed. Please reopen if you see this again.

Resolution - The PASTE option will be shown in the bottom right corner when the keyboard is on.
