### ISSUE TITLE
Select all not working

### ISSUE THREAD

**Issue by NightOwl134** [jsitor/jsitor#26]
When holding the screen to select all the words on the text box, nothin happens. Can you please fix this. Thank you

**Comment by ashvin777** [comment]
Hi , Is it possible to share some more detail when and where this issue is happening. Screenshot will also help.

Is this happening for Android or iOS or Web app ?
Is this happening for editor view ?

**Comment by ashvin777** [comment]
Hi @NightOwl134 , We have fixed some major issues in our app. We are not seeing this issue any more. Request you to verify it in the latest build.

**Comment by ashvin777** [comment]
Closing this ticket as we are not getting any response from a long time. We have fixed some major issues in our app. We are not seeing this issue any more. Feel free to open this issue again if you find this happening again.
