### ISSUE TITLE
html probs

### ISSUE THREAD

**Issue by Austinmac56** [jsitor/jsitor#31]
I can't write a html line of script without them looking red which is error. And it seems the editor doesn't allow HTML5 elements. 
What should I do?

**Comment by ashvin777** [comment]
Hi @Austinmac56 , Sorry not able to understand what exactly is the issue? Can you share more details about it, also if possible please share the screenshot as well. 

Also is this related to Web version or iOS/Android app ? If so can you share the OS details as well.

**Comment by Austinmac56** [comment]
I later got my Android jsitor error resolved. Thanks
