### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by victinni** [jsitor/jsitor#36]
You can’t put pictures in JSitor

**Comment by ashvin777** [comment]
Hi @victinni , 

Please help me to understand this issue better,  Please answer the below questions - 

1. Is it related to Web App(jsitor.com) or Mobile App(JSitor - iOS or Android app)?

2. How exactly you are trying to put pictures? Are you using remote URL(Already supported - Try [https://jsitor.com/CCQwxsbVN](https://jsitor.com/CCQwxsbVN)) ? or you are expecting JSitor to provide you an option to upload images first and use that(By the way it's not supported)?
