### ISSUE TITLE
New Lines not shown in console

### ISSUE THREAD

**Issue by biraj21** [jsitor/jsitor#40]
SM-J710F, Android 8.1.0

\n is not working in the console. it's just showing it as it is in the console("\n")
![Screenshot_20200209-145721_JSitor](https://user-images.githubusercontent.com/37879496/74099715-8dfd3200-4b4c-11ea-9563-7b6d79c7aadf.jpg).

**Comment by ashvin777** [comment]
Thanks @biraj795 , I will look into this.

**Comment by ashvin777** [comment]
Hi @biraj21 , If possible, please share the link of the snippet. We have added a fix and would like to verify it on your snippet.

**Comment by biraj21** [comment]
Now it's fixed.

**Comment by ashvin777** [comment]
Thanks @biraj21 . Closing this
