### ISSUE TITLE
CDN libraries missing if added and then removed

### ISSUE THREAD

**Issue by TBD** [jsitor/jsitor#43]
**Describe the bug**
CDN libraries missing if added and then removed

**To Reproduce**
1. Go to jsitor.com
2. Click on CDN
3. add a library (eg. Bootstrap)
4. remove the added library (click on delete trashcan icon)

**Expected behavior**
the library should be back again in the list

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 80.0.3987.122

**Additional context**
maybe a have a fixed list of "Most used" CDN libraries

**Comment by ashvin777** [comment]
Hi @TBD , I don't understand one thing here, 

> add a library (eg. Bootstrap)
> remove the added library (click on delete trashcan icon)

Add -> and Delete will definitely remove that library from the list then why would it expect

> Expected behavior
> the library should be back again in the list

Either I understood the problem wrong or there is some other issue. Could you please help me out to understand it better?

**Comment by TBD** [comment]
situation: I want to test different libraries so
* I add a library, 
* then remove it 
* and add another

I want to be able to add the first library in one click again.

**Comment by ashvin777** [comment]
Something like quick links or recent links you are expecting?

**Comment by TBD** [comment]
recent links will do

**Comment by ashvin777** [comment]
Hi @TBD , This has been improved a lot in our newer version of jsitor.com. You will find complete new user experience and better way to manage the CDNs. Request you to try it out.

**Comment by ashvin777** [comment]
🎉🎉 Please try our latest, we have improved many things and also fixed this issue.

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
