### ISSUE TITLE
print()  opens the systems printer dialog 

### ISSUE THREAD

**Issue by hellonearthis** [jsitor/jsitor#45]
**Describe the bug**
print()  opens the systems printer dialog when I was using the p5 library.
so trying to type print('p5 console.log'); often means typing print() which blocks everything if it's placed into the draw loop.

**To Reproduce**
1. Go to https://jsitor.com/2VF1DouQN

**Expected behavior**
would like to not see the printer dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/121805/77437561-af3e8700-6e49-11ea-96db-f6bb24454d4e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: chrome
 - Version  80.0.3987.149

**Comment by hellonearthis** [comment]
I see it's a browser thing.  Sp I guess I will have to use p5.print()
![image](https://user-images.githubusercontent.com/121805/77644054-5136ae80-6fc5-11ea-9db1-50753e48edbf.png)

**Comment by ashvin777** [comment]
Thanks @hellonearthis , closing this.
