### ISSUE TITLE
Feature request: Sass preprocessor

### ISSUE THREAD

**Issue by LukoFoks** [jsitor/jsitor#53]
I've been using Sass for months and it's a must-have for me. I think it's different in one important way - I don't have to write these ugly brackets and semicolons. Could you please add Sass to JSitor. It's the only thing that makes me migrate back to CodePen, even I'd like to stay. I'm looking forward using this feature!

**Comment by ashvin777** [comment]
Good request, we will have it for sure in upcoming releases. I have added the story in our task list. Thanks

**Comment by ashvin777** [comment]
Hi @LukoFoks , 
It is now supported in JSitor, Enjoy :) 
![image](https://user-images.githubusercontent.com/8143154/97807457-ebab4e80-1c86-11eb-9bec-98fe5e3e0a96.png)

We will also improve syntax highlight further.

**Comment by LukoFoks** [comment]
Amazing! Pretty fast. I'm awaiting that on mobile devices too. Thanks a lot, much more comfortable...

**Comment by ashvin777** [comment]
Sure Luke, Adding it in mobile will take some time but will add it for sure.

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store.

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
