### ISSUE TITLE
Can't copy 

### ISSUE THREAD

**Issue by ayush487** [jsitor/jsitor#54]
Not able to copy for single lines or some lines when needed 
Only I get a option of select all

**Comment by ashvin777** [comment]
Hi Ayush, Please confirm the mobile os version. Also is it iOS or Android app ?

**Comment by ayush487** [comment]
It's Android 
Lenevo k8+

**Comment by ashvin777** [comment]
Thanks @ayush487 , we have added a possible fix for this issue. Request you to update to the latest version. Please also confirm once updated

**Comment by LukoFoks** [comment]
I've got the updated version of JSitor, but I'm still not able to copy the selected text. The button to do that isn't visible.

![JSitor update 10_10 copy-paste](https://user-images.githubusercontent.com/63813215/96555984-ba12aa80-12b8-11eb-9cea-0660c098eda5.png)

I tested it on my phone (Android 7) and my tablet (Android 9), both running the latest version, but it didn't work for any of them.

**Comment by borxdev** [comment]
Same problem here.
Impossible to select or copy specific block of code.
Asus Zenfone 6.
Android 10.
Jsitor app v4.5.

**Comment by ashvin777** [comment]
Request you to wait for couple days. We are soon going to have a better upgraded verison of the app with the fixes.

Some snapshots
![image](https://user-images.githubusercontent.com/8143154/102850087-9eee2380-443e-11eb-917e-0692a66ad109.png)
![image](https://user-images.githubusercontent.com/8143154/102850094-a281aa80-443e-11eb-8136-598f4cdda4bd.png)

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store.

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
