### ISSUE TITLE
Virtual Backspace key frozen on Android 

### ISSUE THREAD

**Issue by PhilipsEkuma** [jsitor/jsitor#63]
Your app has a serious issue where using the backspace key to delete wrong input does not work. The virtual key just refuses to work. This happens barely a minute into launching the app .

**Comment by ashvin777** [comment]
Hi @PhilipsEkuma , Please share the Android Device and OS Versions.

We will check

**Comment by ashvin777** [comment]
🎉🎉 Please try using latest build, we have improved design and fixed many bugs

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
