### ISSUE TITLE
Impossible to select only a word or specific block of code.

### ISSUE THREAD

**Issue by borxdev** [jsitor/jsitor#64]
**The bug**
Impossible to select a specific text block or copy. Only is possible to select all.

**To Reproduce**
1. Create new code snippet.
2. Write or paste some code.
3. Try to select only a line or a word.
4. Theres no select nodes or select option

**Expected behavior**
Select only a word or any specific part of code.

**Screenshots**
![Screenshot_20201205-174943230.jpg](https://user-images.githubusercontent.com/39737321/101258374-5df9cd80-3722-11eb-8737-cf8432faf004.jpg)
![Screenshot_20201205-175003903.jpg](https://user-images.githubusercontent.com/39737321/101258377-62be8180-3722-11eb-88df-5a96daf65d53.jpg)

**Smartphone:**
 - Device: Asus Zenfone 6
 - OS: Android 10
 - Browser: None. Android app
 - Version: JSitor 4.5

**Comment by ashvin777** [comment]
Request you to wait for couple days. We are soon going to have a better upgraded verison of the app with the fixes.

Some snapshots
![image](https://user-images.githubusercontent.com/8143154/102850087-9eee2380-443e-11eb-917e-0692a66ad109.png)
![image](https://user-images.githubusercontent.com/8143154/102850094-a281aa80-443e-11eb-8136-598f4cdda4bd.png)

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store. We have provided explicit toolbar to handle cut, copy, paste actions. 

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
