### ISSUE TITLE
Unable to paste

### ISSUE THREAD

**Issue by phantom11blaster** [jsitor/jsitor#65]
Hey,
I am unable to paste text on the IPad app. Whenever I try pasting, it just selects the text and never gives an option to paste. Kindly help me with the same.
Edit: if you could add a paste button, it would be amazing.
Thanks and Regards,
Phantom.

**Comment by ashvin777** [comment]
Hi @phantom11blaster , Please confirm the iOS version and JSitor app version. We have fixed this issue in our latest update, hopefully, an update will fix the problem.

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store. We have provided explicit toolbar to handle cut, copy, paste actions. 

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
