### ISSUE TITLE
Spelling mistake appears in snippet name when deleting

### ISSUE THREAD

**Issue by jordan-git** [jsitor/jsitor#66]
I tried making a snippet to see if other people could edit it without my permission. Afterwards I went to delete it and this occurred. You can see that it says 'Delete snippet "Unittled"' despite being named "Untitled" in the background.

![firefox_X09eIxPrgY](https://user-images.githubusercontent.com/19174130/101986890-b8e27600-3c88-11eb-8675-c24158811eaf.png)

**Comment by ashvin777** [comment]
Thanks @jordan-git . We will get it fixed soon.

**Comment by ashvin777** [comment]
Resolved in latest release.
