### ISSUE TITLE
Cannot search for / load many npm libraries

### ISSUE THREAD

**Issue by FredKSchott** [jsitor/jsitor#68]
**Describe the bug**
Can't search for many npm packages (ex: preact)

**Screenshots**

<img width="812" alt="Screen Shot 2020-12-18 at 11 40 34 AM" src="https://user-images.githubusercontent.com/622227/102654691-d9e21580-4125-11eb-8de2-5808ae496b02.png">

**Additional context**

If you're interested in fixing, I'd recommend integrating with [Skypack CDN](https://www.skypack.dev/). It allows you to load any npm package via a single unified ESM interface. The npm search API and auto-complete API are also both public: https://api.skypack.dev/

(Full disclosure: I work on Skypack, happy to answer any questions!)

**Comment by ashvin777** [comment]
This is a great suggestion. We will review this and if usefull, will also implement.

Thanks.

**Comment by FredKSchott** [comment]
np! For reference, Codepen has been integrating with Skypack and might have some interesting features worth referencing: https://blog.codepen.io/2020/12/18/fixing-imports-with-skypack/

**Comment by ashvin777** [comment]
Thanjs for sharing ! This will be helpful.

**Comment by ashvin777** [comment]
Hi @FredKSchott ,
🎉🎉
We did enable the JavaScript modules mode and using that we can now import the npm packages in our snippet.

Checkout this snippets for reference -

https://jsitor.com/Lq7xhzh5W

I hope this implementation resolve this request. Let us know if you have any more suggestions.


Thanks and Happy New Year !! 🎉

**Comment by ashvin777** [comment]
Closing this as this is already supported now.

**Comment by FredKSchott** [comment]
That's great to hear! If you ever want to power the "Add Library" Modal with Skypack as well, you can check out our Search API here:  https://api.skypack.dev/. 

Happy New Year to you as well!
