### ISSUE TITLE
Cannot copy/paste

### ISSUE THREAD

**Issue by aksameet** [jsitor/jsitor#70]
No inline copy/paste on ipadOS v 14.3

**Comment by ashvin777** [comment]
Thanks @aksameet . iOS version comes up with default copy paste feature, I have seen that some of iOS versions were having some issues with that.

In latest iOS, it seems to be showing up properly on tap hold. Did you try holding on cursor ? 

We will also try to make this function explicit to get rid of these issues.

**Comment by ashvin777** [comment]
Any update aksameet ? Are you still facing this issue ?

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store. We have provided explicit toolbar to handle cut, copy, paste actions. 

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773

**Comment by abulka** [comment]
Yes but how do I select text? The usual iOS selection metaphor does not work, no ability to drag to extend the selection. The select button on the toolbar is not enough.
