### ISSUE TITLE
Continue with Github account button is broken in iOS app

### ISSUE THREAD

**Issue by rblakejohnson** [jsitor/jsitor#71]
When the Continue with github account button is tapped it goes to an error page and the app must be force closed 
![C22FD4F9-6361-4550-909C-F1DA57AB4FA2](https://user-images.githubusercontent.com/1006869/103037445-17311380-4529-11eb-8eb9-4e4b54fe4b38.png)

**Comment by ashvin777** [comment]
Thanks @rblakejohnson for reporting this. Please let us know what version of the application you are using?

**Comment by rblakejohnson** [comment]
It’s probably version 4.5 it’s the latest version and that’s what it shows on the App Store page but I can’t find any version info inside the app. 

Thanks,
Blake

**Comment by ashvin777** [comment]
Ok thanks. We tried to reproduce but somehow not able to. We will continue to investigate. 

Does this appear all the time or goes aways after relaunch ? Also can you confirm the internet connection is active when you was trying this ?

**Comment by rblakejohnson** [comment]
That’s weird. It happens every time I’ve tapped the button. Happens after killing the app and relaunching and after deleting the app and reinstalling. I have a good internet connection while doing this. Thanks!

**Comment by ashvin777** [comment]
We were able to reproduce this and fixed this issue. Thanks for reporting this. 
Please confirm.

**Comment by rblakejohnson** [comment]
That’s great, thanks! But how do I confirm? Version 4.5 is latest on App Store

**Comment by ashvin777** [comment]
This was a fix in backend so nothing to update in the app. In the same version it should work without any update.

**Comment by ashvin777** [comment]
This is strange. I can see the page on my side.

Can you try to open github.com in your brwoser and check if domain is accesible to you or not?

![image](https://user-images.githubusercontent.com/8143154/104534024-81753980-5639-11eb-94c9-9ad11e979399.png)

**Comment by rblakejohnson** [comment]
GitHub.com is accessible and I signed in with no problems. 

Thanks,
Blake

**Comment by ashvin777** [comment]
Ok, it could be a caching issue as well. Maybe give a try by restarting the phone ?

**Comment by rblakejohnson** [comment]
I restarted my phone and I still see the same error 😕
I’m out of ideas. This is urgent or anything so thanks for troubleshooting.

**Comment by ashvin777** [comment]
This is bad. 😞 

May I know the iPhone OS Version ?

**Comment by rblakejohnson** [comment]
Sure, iOS 13.6 on an iPhone 8

Thanks,
Blake

**Comment by rblakejohnson** [comment]
I figured out what the issue is for me. I have a DNS server configured for my wifi network that is block the auth url for some reason. So when I turn off wifi and I’m just on phone network I can sign in with github. Sorry for any hassle and thanks for troubleshooting this!

**Comment by ashvin777** [comment]
Awesome, Thanks. Closing this one.
