### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by kennywindis** [jsitor/jsitor#74]
I can’t login why

**Comment by ashvin777** [comment]
Hi Kenny, May I know more details about the issue?

Are you talking about App or Website ?

Are you seeing any error? 

We are not seeing any issue with login, please help us understand this issue better by providing proper context and screenshot if possible.

Thanks

**Comment by kennywindis** [comment]
I logout of the JSitor app when I noticed that it was not saving snippets
for me again and I tried to login it was showing domain error and server
error. I redownloaded the app and its still showing the same error

**Comment by ashvin777** [comment]
Thanks, we are able to reproduce it. We will get it fixed as soon as possible.

Thanks for reporting this issue.

**Comment by ashvin777** [comment]
Please check now. Its resolved

**Comment by kennywindis** [comment]
Yes thank you,it working now but I can’t still save snippets,I have 6
snippets saved on it before and want to save more

**Comment by ashvin777** [comment]
Just now checked, there is no issue with saving snippet. What exactly is the error/issue you are facing while you are trying to save the snippet? 

If you have some snippets that were created while you were logged out, we could try to change the assignment if you share the links of those.

**Comment by kennywindis** [comment]
Ok thank you very much
