### ISSUE TITLE
Feature request: ‘.sass’ syntax support on mobile OS

### ISSUE THREAD

**Issue by ShiBa-Shin** [jsitor/jsitor#76]
It’s very nice to see the editor supports ‘.scss’, but there’re lots of people like me do hope the less of ‘{}’, the better. So would you be kind to add the ‘.sass’ syntax? Thanks for created this wonderful app.

**Comment by ashvin777** [comment]
We will not disappoint you 🙂

That is coming soon. Stay tuned

![image](https://user-images.githubusercontent.com/8143154/106242004-01e88c80-622d-11eb-8fbb-5411ad0b88fa.jpeg)

**Comment by ShiBa-Shin** [comment]
> We will not disappoint you 🙂
> 
> That is coming soon. Stay tuned
> 
> ![image](https://user-images.githubusercontent.com/8143154/106242004-01e88c80-622d-11eb-8fbb-5411ad0b88fa.jpeg)

Thank you so much for quick respond. Looking forward to the update!

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store.

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
