### ISSUE TITLE
File won’t work

### ISSUE THREAD

**Issue by freddinmg** [jsitor/jsitor#85]
Couldn’t find an answer or troubleshoot, so sorry if answered before.

this file won’t work even though I know the code is right. I’m using a tutorial file from a course I’m taking on Udemy. What am I doing wrong? I know that nestled html works (at least, I’ve seen it work) and making the script inline didn’t help. The css works fine. Here is also a link to the file. https://jsitor.com/KC9PljI9x 
![0ECB44E4-D46C-4175-A55D-F9AA38E96003](https://user-images.githubusercontent.com/79553156/116012719-51571280-a5fa-11eb-9cc8-05177718fa6a.png)
![0B559309-5546-4162-909E-3056BDC20458](https://user-images.githubusercontent.com/79553156/116012721-52883f80-a5fa-11eb-9f9d-16a772c52ebf.png)
![07885645-32F6-42A9-A489-BF1DE97069B8](https://user-images.githubusercontent.com/79553156/116012723-5320d600-a5fa-11eb-965e-218c6aaf3aa0.png)

**Comment by freddinmg** [comment]
I figured it out. I'm sorry, it was an easy fix. How do I delete this thread?

**Comment by ashvin777** [comment]
Done, thanks!
