### ISSUE TITLE
please fix this

### ISSUE THREAD

**Issue by Coding94** [jsitor/jsitor#90]
Good morning, I've been having problems when using the keyboard, I've already checked the internet for a possible solution but there doesn't seem to be one. The problem is the same as that of another user, Shiba-shin.  The problem is that when using the app with the keyboard, the cursor disappears and doesn't let me enter anything, when I disconnect the keyboard instead it lets me use the touch of the device. I use a 2015 ipad pro 12.9, of course I use the last version of the app.

**Comment by ashvin777** [comment]
Thanks for reporting this issue. We will try to fix this problem as soon as we can.

**Comment by trytolearncode24** [comment]
ok I'm waiting your news!

**Comment by trytolearncode24** [comment]
any news?

**Comment by ashvin777** [comment]
Yes we hae started working on it, will soon have a fix for this.

**Comment by ashvin777** [comment]
I have added the support for the hardware keyboard and the new update is available in the store. Please try updating your application.

Do let me know as well whether it works or not.
