### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by jfothergill95** [jsitor/jsitor#91]
For some reason I cannot type on the app, I tap where im supposed to type but it just doesn’t doing anything when I try type. What is wrong?

**Comment by ashvin777** [comment]
Hi @jfothergill95 , Please check if you are using the latest version of the app. Also please make sure to share the details of your device and OS for better inevstigation.

**Comment by ashvin777** [comment]
I have added the support for the hardware keyboard and the new update is available in the store. Please try updating your application.

Do let me know as well whether it works or not.
